import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



public class LoginGUI extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form register
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        BTNREGISTER = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        BTNLOGINN = new javax.swing.JButton();
        PWFPASSWORD = new javax.swing.JPasswordField();
        ForgotPass = new javax.swing.JLabel();
        TXTUNAME = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        TXTSHOWPASS = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel49.setText("Don't have an Account?");

        BTNREGISTER.setBackground(new java.awt.Color(255, 204, 0));
        BTNREGISTER.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BTNREGISTER.setText("Register");
        BTNREGISTER.setPreferredSize(new java.awt.Dimension(73, 29));
        BTNREGISTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNREGISTERMouseClicked(evt);
            }
        });
        BTNREGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTERActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel45.setText("Hello, Welcome!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BTNREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel47.setText("Username:");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel48.setText("Password:");

        BTNLOGINN.setBackground(new java.awt.Color(255, 204, 0));
        BTNLOGINN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BTNLOGINN.setText("Login");
        BTNLOGINN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNLOGINNBTNLOGINNMouseClicked(evt);
            }
        });
        BTNLOGINN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLOGINNBTNLOGINNActionPerformed(evt);
            }
        });

        ForgotPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ForgotPass.setText("Forgot your password?");
        ForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassForgotPassLabelMouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel46.setText("Login");

        TXTSHOWPASS.setText("Show");
        TXTSHOWPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSHOWPASSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BTNLOGINN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PWFPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTUNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel47))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ForgotPass)
                        .addGap(3, 3, 3)))
                .addComponent(TXTSHOWPASS)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel46)
                .addGap(26, 26, 26)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTUNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PWFPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTSHOWPASS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForgotPass)
                .addGap(19, 19, 19)
                .addComponent(BTNLOGINN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNREGISTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNREGISTERMouseClicked

        RegisterGUI rg = new RegisterGUI();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BTNREGISTERMouseClicked

    private void BTNREGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTERActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BTNREGISTERActionPerformed

    private void BTNLOGINNBTNLOGINNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNLOGINNBTNLOGINNMouseClicked

    }//GEN-LAST:event_BTNLOGINNBTNLOGINNMouseClicked

    private void BTNLOGINNBTNLOGINNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLOGINNBTNLOGINNActionPerformed

          String username = TXTUNAME.getText();
        String password = new String(PWFPASSWORD.getPassword());

    if (username.isEmpty() || password.isEmpty()) {
       JOptionPane.showMessageDialog(this, "please enter username or password.");
        return;
    }

   try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/appointment_scheduling_system", "root", "");


    // First, check student table
    String sqlStudent = "SELECT * FROM student_tb WHERE UserName = ? AND Password = ?";
    PreparedStatement pstStudent = conn.prepareStatement(sqlStudent);
    pstStudent.setString(1, username);
    pstStudent.setString(2, password);
    ResultSet rsStudent = pstStudent.executeQuery();

    if (rsStudent.next()) {
        JOptionPane.showMessageDialog(this, "Login Successful!");
        
        SystemGUI sys= new SystemGUI();
        sys.setVisible(true);
         sys.pack();
        sys.setLocationRelativeTo(null);
        sys.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
        
        
        // redirect to student dashboard here
    } else {
        // If not found, check mentor table
        String sqlMentor = "SELECT * FROM mentor_tb WHERE UserName = ? AND Password = ?";
        PreparedStatement pstMentor = conn.prepareStatement(sqlMentor);
        pstMentor.setString(1, username);
        pstMentor.setString(2, password);
        ResultSet rsMentor = pstMentor.executeQuery();

        if (rsMentor.next()) {
            JOptionPane.showMessageDialog(this, "Login Successful!");
            
            
              SystemGUI sys= new SystemGUI();
        sys.setVisible(true);
         sys.pack();
        sys.setLocationRelativeTo(null);
        sys.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
            // redirect to mentor dashboard here
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
        }
    }

    conn.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_BTNLOGINNBTNLOGINNActionPerformed

    private void ForgotPassForgotPassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassForgotPassLabelMouseClicked

        Forgotpass fp= new Forgotpass();
        fp.setVisible(true);
        fp.pack();
        fp.setLocationRelativeTo(null);
        fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ForgotPassForgotPassLabelMouseClicked

    private void TXTSHOWPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSHOWPASSActionPerformed
        // TODO add your handling code here:
        if (TXTSHOWPASS.isSelected()) {
            PWFPASSWORD.setEchoChar((char) 0);
            TXTSHOWPASS.setText("Hide Password");
        } else {
            PWFPASSWORD.setEchoChar('•');
            TXTSHOWPASS.setText("Show Password");
        }
    }//GEN-LAST:event_TXTSHOWPASSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLOGINN;
    private javax.swing.JButton BTNREGISTER;
    private javax.swing.JLabel ForgotPass;
    private javax.swing.JPasswordField PWFPASSWORD;
    private javax.swing.JRadioButton TXTSHOWPASS;
    private javax.swing.JTextField TXTUNAME;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
