import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ana
 */
public class RegisterGUI extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CBYL = new javax.swing.JComboBox<>();
        BTNCLEARALLREG = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        BTNSIGNIN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TXTUSERNAME = new javax.swing.JTextField();
        CBSCHOOL = new javax.swing.JComboBox<>();
        TXTPASSWORD = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TXTSHOWPASS = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TXTCONTACTNO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBCOURSE = new javax.swing.JComboBox<>();
        TXTMNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTLNAME = new javax.swing.JTextField();
        TXTADDRESS = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXTFNAME = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TXTEMAILADDRESS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BTNREGISTER = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        CBYL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "1", "2", "3", "4", "5" }));

        BTNCLEARALLREG.setBackground(new java.awt.Color(255, 204, 0));
        BTNCLEARALLREG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNCLEARALLREG.setText("CLEAR ALL");
        BTNCLEARALLREG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNCLEARALLREGMouseClicked(evt);
            }
        });
        BTNCLEARALLREG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCLEARALLREGActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Username:");

        BTNSIGNIN.setBackground(new java.awt.Color(255, 204, 0));
        BTNSIGNIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNSIGNIN.setText("SIGN IN");
        BTNSIGNIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSIGNINActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("School:");

        CBSCHOOL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "PHINMA Cagayan de Oro College", "Liceo de Cagayan University", "Xavier University", "University of Science and Technnology of Southern Philippines" }));
        CBSCHOOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSCHOOLActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Lastname:");

        TXTSHOWPASS.setText("Show");
        TXTSHOWPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSHOWPASSActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Course:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Middlename:");

        CBCOURSE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select---", "BS Information Technology", "BS Civil Enginnering", "BS Electrical Enginnering", "BS Nursing", "BS Mechanical Enginnering", "BS Data Science", "BS Psychology", "BS Medical Technology", "BS Education", "BS Architecture", " " }));
        CBCOURSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCOURSEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Firstname:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Address:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Year Level:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Contact no:");

        TXTFNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFNAMEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Register");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Email Address:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BTNCLEARALLREG, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(BTNSIGNIN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXTCONTACTNO, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CBSCHOOL, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                            .addComponent(CBCOURSE, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBYL, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTUSERNAME)
                            .addComponent(TXTPASSWORD, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTADDRESS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTLNAME, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTMNAME, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTFNAME)
                            .addComponent(TXTEMAILADDRESS))))
                .addGap(18, 18, 18)
                .addComponent(TXTSHOWPASS)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTFNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTMNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTEMAILADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTCONTACTNO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBSCHOOL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCOURSE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBYL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TXTPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTSHOWPASS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCLEARALLREG)
                    .addComponent(BTNSIGNIN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Already have an Account?");

        BTNREGISTER.setBackground(new java.awt.Color(255, 204, 0));
        BTNREGISTER.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BTNREGISTER.setText("Login");
        BTNREGISTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNREGISTERMouseClicked(evt);
            }
        });
        BTNREGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTERActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("Welcome back!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(BTNREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(BTNREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCLEARALLREGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNCLEARALLREGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCLEARALLREGMouseClicked

    private void BTNCLEARALLREGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCLEARALLREGActionPerformed
        // TODO add your handling code here:
        TXTFNAME.setText("");
        TXTMNAME.setText("");
        TXTLNAME.setText("");
        TXTADDRESS.setText("");
        TXTEMAILADDRESS.setText("");
        TXTCONTACTNO.setText("");
        TXTUSERNAME.setText("");
        TXTPASSWORD.setText("");

        CBSCHOOL.setSelectedIndex(0);
        CBCOURSE.setSelectedIndex(0);
        CBYL.setSelectedIndex(0);
    }//GEN-LAST:event_BTNCLEARALLREGActionPerformed

    private void BTNSIGNINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSIGNINActionPerformed
        // TODO add your handling code here:
        String fn = TXTFNAME.getText();
        String mn = TXTMNAME.getText();
        String ln = TXTLNAME.getText();
        String address = TXTADDRESS.getText();
        String ea = TXTEMAILADDRESS.getText();
        String cont = TXTCONTACTNO.getText();
        String school = CBSCHOOL.getSelectedItem().toString();
        String course = CBCOURSE.getSelectedItem().toString();
        String yl = CBYL.getSelectedItem().toString();
        String un = TXTUSERNAME.getText();
        String pass = TXTPASSWORD.getText();

        if (fn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter firstname!");
            return;
        }

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/appointment_scheduling_system", "root", "");

            String checkUser = "SELECT * FROM student_tb WHERE UserName = ?";
            pst = con.prepareStatement(checkUser);
            pst.setString(1, un);
            rs = pst.executeQuery();

            if (rs.next()) {

                JOptionPane.showMessageDialog(null, "The username has been taken!");
                return;
            }

            String sql = "INSERT INTO student_tb (FirstName, MiddleName, LastName, Address, EmailAddress, ContactNo, School, Course, YearLevel, UserName, Password) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, fn);
            pst.setString(2, mn);
            pst.setString(3, ln);
            pst.setString(4, address);
            pst.setString(5, ea);
            pst.setString(6, cont);
            pst.setString(7, school);
            pst.setString(8, course);
            pst.setString(9, yl);
            pst.setString(10, un);
            pst.setString(11, pass);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registered Successfully!");

            LoginGUI lg = new LoginGUI();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BTNSIGNINActionPerformed

    private void CBSCHOOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSCHOOLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSCHOOLActionPerformed

    private void TXTSHOWPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSHOWPASSActionPerformed
        // TODO add your handling code here:
        if (TXTSHOWPASS.isSelected()) {
            TXTPASSWORD.setEchoChar((char) 0);
            TXTSHOWPASS.setText("Hide Password");
        } else {
            TXTPASSWORD.setEchoChar('•');
            TXTSHOWPASS.setText("Show Password");
        }
    }//GEN-LAST:event_TXTSHOWPASSActionPerformed

    private void CBCOURSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCOURSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCOURSEActionPerformed

    private void TXTFNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFNAMEActionPerformed

    }//GEN-LAST:event_TXTFNAMEActionPerformed

    private void BTNREGISTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNREGISTERMouseClicked
        LoginGUI lg = new LoginGUI();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BTNREGISTERMouseClicked

    private void BTNREGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNREGISTERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCLEARALLREG;
    private javax.swing.JButton BTNREGISTER;
    private javax.swing.JButton BTNSIGNIN;
    private javax.swing.JComboBox<String> CBCOURSE;
    private javax.swing.JComboBox<String> CBSCHOOL;
    private javax.swing.JComboBox<String> CBYL;
    private javax.swing.JTextField TXTADDRESS;
    private javax.swing.JTextField TXTCONTACTNO;
    private javax.swing.JTextField TXTEMAILADDRESS;
    private javax.swing.JTextField TXTFNAME;
    private javax.swing.JTextField TXTLNAME;
    private javax.swing.JTextField TXTMNAME;
    private javax.swing.JPasswordField TXTPASSWORD;
    private javax.swing.JRadioButton TXTSHOWPASS;
    private javax.swing.JTextField TXTUSERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
